export type ClientOverview = {
  product: string;
  profile: {
    id: string;
    clientCode: string | null;
    name: string;
    email: string | null;
    telegram: string | null;
    localLogin: string | null;
    createdAt: string;
    lastActivityAt: string | null;
    notificationFeedSeenAt: string | null;
    notificationFeedClearedAt: string | null;
    status: string;
    balance: number;
    balanceLabel: string;
    referralCode: string;
    referralLink: string;
    hasOpenTwoFactorRequest: boolean;
    hasOpenDeletionRequest: boolean;
  };
  sessions: Array<{
    id: string;
    isCurrent: boolean;
    createdAt: string;
    lastSeenAt: string;
    expiresAt: string;
    userAgent: string | null;
    ipAddress: string | null;
  }>;
  links: {
    apiUrl: string;
    appUrl: string;
    support: string;
    telegramBot: string;
    telegramChannel: string;
  };
  paymentMethods: Array<{
    id: "platega" | "yoomoney" | "yookassa";
    label: string;
    description: string;
    enabled: boolean;
  }>;
  stats: {
    routerCount: number;
    activeRouterCount: number;
    openTicketCount: number;
    unreadNotificationCount: number;
  };
  catalog: {
    periodDays: number;
    extendedAccessPrice: number;
    basicSupportPrice: number;
    extendedSupportPrice: number;
    recommendedPrice: number;
    recommendedPriceLabel: string;
    recommendedPackage: string;
  };
  orderOffer: {
    routerPrice: number;
    routerPriceLabel: string;
    setupPrice: number;
    setupPriceLabel: string;
    totalPrice: number;
    totalPriceLabel: string;
  };
  routers: Array<{
    id: string;
    routerCode: string | null;
    displayName: string;
    model: string | null;
    serialNumber: string | null;
    configurationType: string;
    status: string;
    adminNote: string | null;
    currentPackage: string;
    lastCheckAt: string | null;
    lastCheckReachable: boolean | null;
    currentSubscription: {
      accessEnabled: boolean;
      supportType: string;
      status: string;
      startAt: string | null;
      endAt: string | null;
      daysRemaining: number | null;
      price: number;
      priceLabel: string;
      pendingActivation: boolean;
    } | null;
    savedTemplate: {
      accessEnabled: boolean;
      supportType: string;
      label: string;
      nextPrice: number;
      nextPriceLabel: string;
    };
    recentPayments: Array<{
      id: string;
      status: string;
      amount: number;
      amountLabel: string;
      createdAt: string;
    }>;
    recentTickets: Array<{
      id: string;
      number: number;
      category: string;
      status: string;
      updatedAt: string;
    }>;
    trial: {
      used: boolean;
      startAt: string | null;
      endAt: string | null;
      daysRemaining: number | null;
    } | null;
  }>;
  orders: Array<{
    id: string;
    status: string;
    totalPrice: number;
    totalPriceLabel: string;
    trackingNumber: string | null;
    createdAt: string;
    receivedAt: string | null;
  }>;
  tickets: Array<{
    id: string;
    number: number;
    category: string;
    description: string;
    status: string;
    routerId: string | null;
    adminComment: string | null;
    adminCommentUpdatedAt: string | null;
    createdAt: string;
    updatedAt: string;
    messages: Array<{
      id: string;
      authorRole: "CLIENT" | "ADMIN";
      body: string;
      createdAt: string;
    }>;
  }>;
  payments: Array<{
    id: string;
    daysAdded: number | null;
    amount: number;
    amountLabel: string;
    provider: string;
    providerLabel: string;
    status: string;
    routerName: string | null;
    createdAt: string;
    paidAt: string | null;
    paymentUrl: string | null;
  }>;
  referrals: {
    invitedCount: number;
    availableRewards: number;
    availableRewardsLabel: string;
    pendingRewards: number;
    pendingRewardsLabel: string;
    items: Array<{
      id: string;
      referredUserId: string;
      createdAt: string;
      referredCreatedAt: string;
    }>;
  };
  rewards: Array<{
    id: string;
    sourceType: string;
    sourceId: string;
    amount: number;
    amountLabel: string;
    status: string;
    createdAt: string;
    availableAt: string | null;
  }>;
  notifications: Array<{
    id: string;
    type: string;
    createdAt: string;
    readAt: string | null;
    title: string;
    detail: string;
    href: string;
  }>;
  notificationFeedAsOf: string;
  notificationFeedHasMore: boolean;
};

export type AdminClientDevice = {
  id: string; routerCode: string | null; displayName: string; plan: string; price: number; priceLabel: string;
  model: string | null; serialNumber: string | null; configurationType: string; status: string; adminNote: string | null;
  imported: boolean;
  archivedAt: string | null;
  subscriptions: Array<{ id: string; accessEnabled: boolean; supportType: string; endAt: string | null; startAt: string | null; daysRemaining: number | null; status: string; pendingActivation: boolean; pendingDays: number; isTrial: boolean }>;
  payments: Array<{ id: string; status: string; amount: number; amountLabel: string; paidAt: string | null; daysAdded: number | null; imported: boolean; provider: string; allocationNeeded: boolean }>;
};
export type AdminMoneyDetail = { id: string; userId: string; clientCode: string | null; name: string | null; routerCode: string | null; amount: number; at: string; provider?: string; plan?: string };
export type AdminOverview = {
  integrations: Array<{id:string;label:string;enabled:boolean;ready:boolean}>;
  registerMeta: Record<string,{total:number;page:number;pageSize:number}>;
  administrators: Array<{id:string;name:string|null}>;
  currentAdmin: string;
  reconciliation: Array<{ routerId: string; code: string | null; object: string; currentPlan: string | null; expectedPlan: string | null; currentPrice: number; expectedPrice: number; importedAmount: number; expectedAmount: number; currentEnd: string | null; expectedEnd: string | null; eligible: boolean; completed: boolean; state: string; source: string }>;
  clientCount: number;
  clientQuery: string;
  clientPage: number;
  clientPageSize: number;
  clientPlan: string;
  clientStatus: string;
  clientCity: string;
  clientSort: "created" | "name" | "code" | "end";
  clientExpiry: string;
  selection: {
    routers: number;
    periodPrice: number;
    payments: number;
  };
  stats: {
    users: number;
    routers: number;
    activeSubscriptions: number;
    openTickets: number;
  };
  dashboard: {
    paidSubscriptions: number;
    expiringSubscriptions: number;
    newTickets: number;
    month: string;
    totalClients: number;
    activeClients: number;
    confirmedPayments: number;
    confirmedPaymentsLabel: string;
    refunds: number;
    refundsLabel: string;
    nextMonthForecast: number;
    nextMonthForecastLabel: string;
    nextMonthRouters: number;
    activeDevices: number;
    selfServiceClients: number;
    freeTests: number;
    asOf: string;
    nextMonth: string;
    archivedClients: number;
    testClients: number;
    activeSubscriptions: number;
    overdue: number;
    nextMonthOrders: number;
    paymentDetails: AdminMoneyDetail[];
    refundDetails: AdminMoneyDetail[];
    forecastDetails: AdminMoneyDetail[];
  };
  settings: Array<{
    defaultValue: string;
    description: string;
    group: string;
    input: "boolean" | "number" | "password" | "text" | "url";
    key: string;
    label: string;
    public: boolean;
    value: string;
  }>;
  users: Array<{
    id: string;
    trialReceivedOrders: number;
    trialUsed: number;
    archivedAt: string | null;
    clientCode: string | null;
    phone: string | null;
    city: string | null;
    name: string | null;
    email: string | null;
    telegram: string | null;
    telegramUsername: string | null;
    hasTelegramIdentity: boolean;
    status: string;
    balance: number;
    balanceLabel: string;
    routerCount: number;
    referralCode: string;
    createdAt: string;
    lastActivityAt: string | null;
  }>;
  clients: Array<{
    id: string;
    clientCode: string | null;
    phone: string | null;
    city: string | null;
    name: string | null;
    email: string | null;
    telegram: string | null;
    telegramUsername: string | null;
    hasTelegramIdentity: boolean;
    status: string;
    balance: number;
    balanceLabel: string;
    routerCount: number;
    referralCode: string;
    createdAt: string;
    lastActivityAt: string | null;
    serviceState: string;
    archivedAt: string | null;
    isTest: boolean;
    active: boolean;
    devices: AdminClientDevice[];
    localLogin: string | null;
    publicName: string | null;
  }>;
  routers: Array<{
    id: string;
    routerCode: string | null;
    clientCode: string | null;
    serviceTariff: string | null;
    displayName: string;
    model: string | null;
    serialNumber: string | null;
    configurationType: string;
    status: string;
    ownerId: string;
    archivedAt: string | null;
    ownerName: string;
    savedTemplate: string;
    planPrice: number;
    planPeriodDays: number;
    planAccessEnabled: boolean;
    planSupportType: string;
    adminNote: string | null;
    monitorHost: string | null;
    monitorPort: number | null;
    services: Array<{id:string;accessEnabled:boolean;supportType:string;endAt:string|null;startAt:string|null;pendingActivation:boolean;pendingDays:number}>;
    endAt: string | null;
    daysRemaining: number | null;
    pendingActivation: boolean;
    paidActive: boolean;
    plan: string;
    createdAt: string;
  }>;
  subscriptions: Array<{
    id: string;
    routerId: string;
    routerName: string;
    routerCode: string | null;
    daysRemaining: number | null;
    payments: Array<{ id: string; amountLabel: string; daysAdded: number | null; paidAt: string | null; provider: string }>;
    bundleLabel: string;
    status: string;
    startAt: string | null;
    endAt: string | null;
    price: number;
    priceLabel: string;
    accessEnabled: boolean;
    supportType: string;
    pendingActivation: boolean;
    pendingDays: number;
    clientCode: string | null;
    userId: string;
    customerName: string | null;
    paidActive: boolean;
    isTrial: boolean;
    periodDays: number;
    nextPrice: number;
  }>;
  orders: Array<{
    id: string;
    userId: string;
    clientCode: string | null;
    customerName: string;
    status: string;
    totalPrice: number;
    totalPriceLabel: string;
    trackingNumber: string | null;
    createdAt: string;
    receivedAt: string | null;
  }>;
  tickets: Array<{
    id: string;
    number: number;
    userId: string;
    routerId: string | null;
    customerName: string;
    clientCode: string | null;
    routerCode: string | null;
    guestContact: string | null;
    contact: string | null;
    routerName: string;
    category: string;
    description: string;
    status: string;
    assigneeId: string | null;
    adminComment: string | null;
    adminCommentUpdatedAt: string | null;
    createdAt: string;
    updatedAt: string;
    archivedAt: string | null;
    messages: Array<{
      id: string;
      authorRole: "CLIENT" | "ADMIN";
      body: string;
      createdAt: string;
    }>;
  }>;
  rewardTotals: {pending:number;available:number;canceled:number};
  rewards: Array<{
    id: string;
    amount: number;
    amountLabel: string;
    status: string;
    sourceType: string;
    sourceId: string;
    paymentId: string | null;
    beneficiaryName: string | null;
    beneficiaryCode: string | null;
    referredName: string | null;
    referredCode: string | null;
    referrerName: string | null;
    referrerCode: string | null;
    availableAt: string | null;
    createdAt: string;
  }>;
  logs: Array<{
    id: string;
    admin: string;
    beforeData: unknown;
    afterData: unknown;
    action: string;
    entityType: string;
    entityId: string;
    href: string | null;
    objectLabel: string;
    createdAt: string;
  }>;
};
