"use client";
import { useState } from "react";
import type { AdminOverview } from "../lib/portal-types";
import { adminMoney } from "../lib/admin-display";
export function AdminAssignment({ users }: { users: AdminOverview["users"] }) {
  const [query,setQuery]=useState(""),[userId,setUser]=useState(""),[plan,setPlan]=useState("Сервер"),[price,setPrice]=useState(1000),[trial,setTrial]=useState(false),[individualAccess,setIndividualAccess]=useState(false),[individualSupport,setIndividualSupport]=useState("NONE");
  const customer=users.find(u=>u.id===userId); const trialEligible=!!customer && customer.trialReceivedOrders>customer.trialUsed;
  const matches=users.filter(u=>!u.archivedAt && [u.clientCode,u.name,u.phone,u.email,u.telegram].join(" ").toLowerCase().includes(query.toLowerCase())).slice(0,30);
  return <form data-admin-path="/api/admin/routers" className="contentStack">
    <input type="hidden" name="userId" value={userId}/>
    <label><span className="fieldLabel">Найти клиента: CLI, имя, контакт</span><input className="textInput" type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label>
    <div className="adminClientChooser" role="listbox" aria-label="Клиент">{matches.map(u=><button key={u.id} type="button" className="secondaryButton" aria-selected={u.id===userId} onClick={()=>{setUser(u.id);setTrial(false);}}>{u.id===userId?"✓ ":""}{u.clientCode} · {u.name??"Без имени"} · {u.phone??u.telegram??""}</button>)}{!matches.length?<p>Подходящих рабочих клиентов нет.</p>:null}</div>
    <p className="helperText">Нового клиента можно создать ниже. Архивные клиенты скрыты из выбора.</p>
    <div className="settingsGrid"><label><span className="fieldLabel">Название / SPB</span><input className="textInput" name="displayName" minLength={2} required/></label><label><span className="fieldLabel">Модель</span><input className="textInput" name="model"/></label><label><span className="fieldLabel">Серийный номер</span><input className="textInput" name="serialNumber"/></label><label><span className="fieldLabel">Техническая конфигурация</span><select className="textInput" name="configurationType"><option value="BASIC">Базовая</option><option value="EXTENDED">Расширенная</option></select></label><label><span className="fieldLabel">Бизнес-план</span><select className="textInput" name="serviceTariff" value={plan} onChange={e=>{setPlan(e.target.value);setPrice(e.target.value==="Самостоятельно"?0:e.target.value==="Индивидуальный"?0:e.target.value==="Полный"?2000:1000);if(e.target.value==="Самостоятельно")setTrial(false);}}>{["Сервер","Техничка","Полный","Самостоятельно","Индивидуальный"].map(p=><option key={p}>{p}</option>)}</select></label><label><span className="fieldLabel">Согласованная цена, ₽</span><input className="textInput" type="number" name="planPrice" min={plan==="Самостоятельно"?0:0.01} max="1000000" step="0.01" value={price} onChange={e=>setPrice(Number(e.target.value))} required/></label><label><span className="fieldLabel">Длительность индивидуального периода, дней</span><input className="textInput" name="planPeriodDays" type="number" min="1" max="3650" defaultValue={30} readOnly={plan!=="Индивидуальный"}/></label></div>
    <label className="checkboxRow"><input name="accessEnabled" type="checkbox" checked={plan==="Индивидуальный"?individualAccess:["Сервер","Полный"].includes(plan)} readOnly={plan!=="Индивидуальный"} onChange={e=>setIndividualAccess(e.target.checked)}/> Серверный доступ в составе плана</label><label><span className="fieldLabel">Сопровождение</span><select className="textInput" name="supportType" value={plan==="Индивидуальный"?individualSupport:["Техничка","Полный"].includes(plan)?"BASIC":"NONE"} onChange={e=>setIndividualSupport(e.target.value)}><option value="NONE">Нет</option><option value="BASIC">Базовое</option><option value="EXTENDED">Расширенное</option></select></label>
    <label className="checkboxRow"><input name="startTrial" type="checkbox" checked={trial} disabled={plan==="Самостоятельно"||!trialEligible} onChange={e=>setTrial(e.target.checked)}/> Подготовить 14-дневный тест после получения роутера проекта</label><p className="helperText">Состав теста совпадает с выбранным доступом и сопровождением; срок — 14 дней после ручной активации. Полученных заказов: {customer?.trialReceivedOrders??0}; использованных тестов: {customer?.trialUsed??0}. {trialEligible?"Тест разрешён по полученному заказу.":"Для теста нужен полученный роутер проекта без использованного периода."} Создание без оплаты не начисляет бесплатные дни.</p>
    <div className="settingsGrid"><label><span className="fieldLabel">IP для проверки · необязательно</span><input className="textInput" name="monitorHost" placeholder="Только явно заданный IP"/></label><label><span className="fieldLabel">Порт для проверки</span><input className="textInput" name="monitorPort" type="number" min="1" max="65535" defaultValue={443}/></label></div><label><span className="fieldLabel">Внутренняя заметка</span><textarea className="textAreaInput" name="adminNote"/></label>
    <p className="helperText">{users.find(u=>u.id===userId)?.clientCode??"Клиент не выбран"} · {plan} · {adminMoney(price)} за период. {trial?"Тест: 14 дней после активации.":"Без теста; ожидает оплаты и активации."}</p>
    <button type="submit" disabled={!userId} className="primaryButton" data-confirm="Создать роутер с показанными условиями?">Привязать роутер</button>
  </form>;
}
export function AdminCreateClient() { return <details className="adminClientEdit"><summary>Создать клиента</summary><form data-admin-path="/api/admin/users" className="contentStack"><div className="settingsGrid"><label><span className="fieldLabel">Имя</span><input className="textInput" name="name" required minLength={2} maxLength={120}/></label><label><span className="fieldLabel">Публичное имя</span><input className="textInput" name="publicName" maxLength={120}/></label><label><span className="fieldLabel">Телефон</span><input className="textInput" name="phone" maxLength={120}/></label><label><span className="fieldLabel">Город</span><input className="textInput" name="city" maxLength={120}/></label><label><span className="fieldLabel">Контакт Telegram · не привязка входа</span><input className="textInput" name="contactTelegram" maxLength={120}/></label></div><button className="secondaryButton" type="submit">Создать клиента без выдачи пароля</button></form></details>; }
